[package]
name = "ymsync-gui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow = "1.0.104"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tauri = { version = "2.11.5", features = ["devtools"] }
tokio = { version = "1.53.1", features = ["rt-multi-thread", "sync", "time"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
ymsync = { version = "0.1.0", path = "../app" }
ymsync-proto = { version = "0.1.0", path = "../proto" }

[build-dependencies]
tauri-build = "2.6.3"
